server:
  port: 8082
spring:
  application:
    name: "bootcamp"
  devtools:
    add-properties: true
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true

entries:
  reactive-web:
    basePath: "/bootcamp"